services:
  backend:
    build:
      context: ./BackEnd
      dockerfile: Dockerfile
    container_name: reminder-backend
    ports:
      - "8080:8080"
    volumes:
      - ./BackEnd:/var/www/html
    depends_on:
      - db
    networks:
      - reminder
  frontend:
    build:
      context: ./FrontEnd
      dockerfile: Dockerfile
    container_name: reminder-frontend
    ports:
      - "3000:3000" 
    volumes:
      - ./FrontEnd:/app
      - /app/node_modules 
    networks:
      - reminder
  nginx:
    image: nginx:alpine
    container_name: reminder-nginx
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
    networks:
      - reminder

  db:
    image: mysql:8.0
    container_name: p-db
    environment:
      MYSQL_DATABASE: reminder
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: reminder
      MYSQL_PASSWORD: reminder
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - reminder

networks:
  reminder:

volumes:
  dbdata:
